
# Only run pipelines for merge requests, tags, and protected branches.
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"

.base:
  image: clfoundation/$LISP:latest
  variables:
    LISP: sbcl
    QUICKLISP_ADD_TO_INIT_FILE: "true"
    QUICKLISP_DIST_VERSION: "latest"
  before_script:
    - install-quicklisp
  script:
    - make test

doc:
  extends: .base
  script:
    - make doc
  artifacts:
    paths:
      - public

pages:
  needs:
    - job: doc
      artifacts: true
  script:
    - echo "nothing to do!"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

test:
  extends: .base
  variables:
    LISP: sbcl
  parallel:
    matrix:
      - STACK:
          - sbcl
          # TODO
          # - abcl
          # - ccl
          # - ecl

# TODO "make demo" is currently broken
# demo:
#   # https://hub.docker.com/_/docker/tags
#   image: docker:24.0.7
#   script:
#     - make demo
#   artifacts:
#     paths:
#       - demo.tgz
