
# Only run pipelines for merge requests, tags, and protected branches.
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"

.base:
  image: clfoundation/$LISP:latest
  variables:
    LISP: sbcl
    QUICKLISP_ADD_TO_INIT_FILE: "true"
    QUICKLISP_DIST_VERSION: "latest"
  before_script:
    - install-quicklisp
  script:
    - make test
  rules:
    - when: manual

test:
  extends: .base
  variables:
    LISP: sbcl
  parallel:
    matrix:
      - STACK:
          - sbcl
          # TODO
          # - abcl
          # - ccl
          # - ecl
  # There's a test that generates some documentation
  artifacts:
    paths:
      - public

# Build public/ folder using org-publish on docs/
org-mode-publish:
  image: docker:24.0.7
  services:
    - docker:24.0.5-dind
  script:
    - apk add --no-cache make
    - make public
    - mv public org-mode-publish
  artifacts:
    paths:
      - org-mode-publish
  rules:
    - when: manual

# Merge "test" and "org-mode-publish"'s outputs
doc:
  needs:
    - job: test
      parallel:
        matrix:
          - STACK:
            - sbcl
      artifacts: true
    - job: org-mode-publish
      artifacts: true
  script:
    - cp org-mode-publish/* public/
  artifacts:
    paths:
      - public

pages:
  needs:
    - job: doc
      artifacts: true
  script:
    - echo "nothing to do!"
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - when: manual
